#!/usr/bin/env python3
"""Feed matched real or rendered surround views to UniAD/VAD in open loop.

The paper specifies that rendered and real observations use the same driving
states, but does not publish its frame list or CAN-bus extraction.  H-DATA-04
reconstructs those states deterministically from the released HUGSIM camera
trajectory and holds every non-image input fixed across visual variants.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import pickle
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import cv2
from omegaconf import OmegaConf
from scipy.spatial.transform import Rotation as Rotation

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from sim.utils.launch_ad import fifo_receive, fifo_send, launch, terminate
from sim.utils.sim_utils import load_camera_cfg


CAMERAS = (
    "CAM_FRONT",
    "CAM_FRONT_RIGHT",
    "CAM_FRONT_LEFT",
    "CAM_BACK",
    "CAM_BACK_LEFT",
    "CAM_BACK_RIGHT",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pairs", type=Path, required=True, help="Held-out pairs.json")
    parser.add_argument(
        "--image-source",
        choices=("target", "pred", "native"),
        required=True,
        help=(
            "target/pred select paths in pairs.json; native selects original "
            "1600x900 nuScenes images from --protocol"
        ),
    )
    parser.add_argument("--label", required=True, help="Stable result label, e.g. real or compact")
    parser.add_argument("--planner", choices=("uniad", "vad"), default="uniad")
    parser.add_argument("--camera-config", type=Path, default=ROOT / "configs/sim/nuscenes_camera.yaml")
    parser.add_argument("--kinematic-config", type=Path, default=ROOT / "configs/sim/decouplegs_kinematic.yaml")
    parser.add_argument(
        "--protocol",
        type=Path,
        help=(
            "Official nuScenes keyframe protocol generated by "
            "prepare_decouplegs_open_loop_protocol.py"
        ),
    )
    parser.add_argument("--output-root", type=Path, default=ROOT / "results/decouplegs/open-loop")
    parser.add_argument("--cuda", default="0")
    parser.add_argument(
        "--planner-color-contract",
        choices=("caffe_bgr", "legacy_rgb_as_bgr"),
        default="caffe_bgr",
        help="Planner preprocessing ablation; official checkpoints use caffe_bgr",
    )
    parser.add_argument(
        "--planner-preprocess-contract",
        choices=("official", "official_uniad", "legacy_hugsim"),
        default="official",
        help="Planner-specific official test pipeline or released HUGSIM adapter",
    )
    parser.add_argument("--limit-timestamps", type=int)
    parser.add_argument("--timeout-seconds", type=float, default=120.0)
    return parser.parse_args()


def exact_camera(frame: dict[str, Any]) -> str:
    return Path(str(frame["rgb_path"])).parent.name


def load_scene_frames(source_path: Path) -> tuple[dict[str, list[dict[str, Any]]], list[int]]:
    metadata = json.loads((source_path / "meta_data.json").read_text())
    by_camera = {camera: [] for camera in CAMERAS}
    for frame in metadata["frames"]:
        camera = exact_camera(frame)
        if camera in by_camera:
            by_camera[camera].append(frame)
    for camera, frames in by_camera.items():
        frames.sort(key=lambda item: float(item["timestamp"]))
        if not frames:
            raise ValueError(f"metadata contains no {camera} frames")
    # Commands are part of HUGSIM's released replay state rather than the
    # camera metadata. The caller replaces this placeholder from model_path.
    return by_camera, []


def route_state(
    front_frames: list[dict[str, Any]], camera_rect: np.ndarray, wheelbase: float
) -> dict[str, np.ndarray]:
    timestamps = np.asarray([float(frame["timestamp"]) for frame in front_frames], dtype=np.float64)
    camera_poses = np.asarray([frame["camtoworld"] for frame in front_frames], dtype=np.float64)
    ego_poses = camera_poses @ np.linalg.inv(camera_rect)[None]
    positions_world = ego_poses[:, :3, 3]
    rotations = np.asarray(
        [Rotation.from_matrix(pose[:3, :3]).as_euler("XYZ") for pose in ego_poses]
    )
    route_xy = np.stack((positions_world[:, 2], -positions_world[:, 0]), axis=-1)
    velocity_xy = np.gradient(route_xy, timestamps, axis=0, edge_order=2)
    speed = np.linalg.norm(velocity_xy, axis=-1)
    acceleration = np.gradient(speed, timestamps, edge_order=2)
    yaw = np.unwrap(-rotations[:, 1])
    yaw_rate = np.gradient(yaw, timestamps, edge_order=2)
    steer = np.arctan2(yaw_rate * wheelbase, np.maximum(speed, 1e-3))
    steer_rate = np.gradient(steer, timestamps, edge_order=2)
    return {
        "timestamps": timestamps,
        "ego_poses": ego_poses,
        "ego_rotations": rotations,
        "route_xy": route_xy,
        "speed": speed,
        "acceleration": acceleration,
        "yaw": yaw,
        "steer": steer,
        "steer_rate": steer_rate,
    }


def nearest_index(timestamps: np.ndarray, timestamp: float) -> int:
    index = int(np.searchsorted(timestamps, timestamp))
    candidates = [min(max(index, 0), len(timestamps) - 1)]
    if index > 0:
        candidates.append(index - 1)
    return min(candidates, key=lambda item: abs(float(timestamps[item]) - timestamp))


def interpolate_xy(state: dict[str, np.ndarray], query: np.ndarray) -> np.ndarray:
    timestamps = state["timestamps"]
    route_xy = state["route_xy"]
    return np.stack(
        (
            np.interp(query, timestamps, route_xy[:, 0]),
            np.interp(query, timestamps, route_xy[:, 1]),
        ),
        axis=-1,
    )


def ground_truth_local_trajectory(
    state: dict[str, np.ndarray], index: int, horizons: np.ndarray
) -> np.ndarray | None:
    now = float(state["timestamps"][index])
    query = now + horizons
    if float(query[-1]) > float(state["timestamps"][-1]):
        return None
    current = state["route_xy"][index]
    future = interpolate_xy(state, query)
    yaw = float(state["yaw"][index])
    heading = np.asarray((math.cos(yaw), math.sin(yaw)))
    lateral_axis = np.asarray((-math.sin(yaw), math.cos(yaw)))
    delta = future - current
    forward = delta @ heading
    lateral = delta @ lateral_axis
    # Planner convention: x points right, y points forward.
    return np.stack((-lateral, forward), axis=-1)


def dynamic_centers(frame: dict[str, Any]) -> dict[str, np.ndarray]:
    centers = {}
    for track_id, transform in (frame.get("dynamics", {}) or {}).items():
        matrix = np.asarray(transform, dtype=np.float64)
        centers[str(track_id)] = np.asarray((matrix[2, 3], -matrix[0, 3]))
    return centers


def paper_literal_plan_ttc(
    plan: np.ndarray,
    state: dict[str, np.ndarray],
    front_frames: list[dict[str, Any]],
    index: int,
    horizons: np.ndarray,
) -> float | None:
    """H-METRIC-02: apply the supplement's distance/relative-speed equation.

    The unpublished detail is how open-loop plans are synchronized with log
    actors. We use nearest released timestamps for actors and the planner's
    fixed 0.5 s trajectory samples for ego velocity.
    """

    horizons = horizons[: len(plan)]
    now = float(state["timestamps"][index])
    if not len(horizons) or now + float(horizons[-1]) > float(state["timestamps"][-1]):
        return None
    yaw = float(state["yaw"][index])
    heading = np.asarray((math.cos(yaw), math.sin(yaw)))
    lateral_axis = np.asarray((-math.sin(yaw), math.cos(yaw)))
    current = state["route_xy"][index]
    plan_global = (
        current[None]
        + plan[:, 1:2] * heading[None]
        - plan[:, 0:1] * lateral_axis[None]
    )
    ego_positions = np.concatenate((current[None], plan_global), axis=0)
    sample_times = np.concatenate((np.zeros(1), horizons))
    ego_velocity = np.diff(ego_positions, axis=0) / np.diff(sample_times)[:, None]

    previous_actor = dynamic_centers(front_frames[index])
    values: list[float] = []
    for horizon_index, horizon in enumerate(horizons):
        actor_index = nearest_index(state["timestamps"], now + float(horizon))
        actors = dynamic_centers(front_frames[actor_index])
        delta_t = float(horizon if horizon_index == 0 else horizon - horizons[horizon_index - 1])
        for track_id, actor_position in actors.items():
            if track_id not in previous_actor:
                continue
            actor_velocity = (actor_position - previous_actor[track_id]) / max(delta_t, 1e-6)
            relative_speed = float(np.linalg.norm(ego_velocity[horizon_index] - actor_velocity))
            if relative_speed > 1e-6:
                distance = float(np.linalg.norm(plan_global[horizon_index] - actor_position))
                values.append(distance / relative_speed)
        previous_actor = actors
    return min(values) if values else None


def info_for_index(
    index: int,
    state: dict[str, np.ndarray],
    cam_params: dict[str, Any],
    commands: list[int],
) -> dict[str, Any]:
    pose = state["ego_poses"][index]
    return {
        "ego_pos": pose[:3, 3].tolist(),
        "ego_rot": state["ego_rotations"][index].tolist(),
        "ego_velo": float(state["speed"][index]),
        "ego_steer": float(state["steer"][index]),
        "accelerate": float(state["acceleration"][index]),
        "steer_rate": float(state["steer_rate"][index]),
        "timestamp": float(state["timestamps"][index]),
        "command": int(commands[min(index, len(commands) - 1)]),
        "cam_params": cam_params,
    }


def wait_for_process(process: subprocess.Popen, timeout: float) -> int:
    try:
        return process.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        return terminate(process)


def load_rgb(path: Path) -> np.ndarray:
    """Decode through OpenCV like the official mmcv image loader, then expose RGB."""

    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        raise FileNotFoundError(f"could not decode image: {path}")
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


def main() -> None:
    args = parse_args()
    payload = json.loads(args.pairs.read_text())
    source_path = Path(payload["source_path"])
    model_path = Path(payload["model_path"])
    frames_by_camera, _ = load_scene_frames(source_path)
    front_frames = frames_by_camera["CAM_FRONT"]

    camera_cfg = OmegaConf.load(args.camera_config)
    cam_params, _, camera_rect = load_camera_cfg(camera_cfg)
    kinematic = OmegaConf.load(args.kinematic_config)
    wheelbase = float(kinematic.Lr + kinematic.Lf)
    state = route_state(front_frames, camera_rect, wheelbase)
    with (model_path / "ground_param.pkl").open("rb") as handle:
        _, _, commands = pickle.load(handle)

    protocol_payload = None
    protocol_by_sample: dict[str, dict[str, Any]] = {}
    if args.protocol is not None:
        protocol_payload = json.loads(args.protocol.read_text())
        if protocol_payload.get("benchmark") != "decouplegs_nuscenes_open_loop_protocol":
            raise ValueError(f"not a nuScenes open-loop protocol: {args.protocol}")
        protocol_by_sample = {
            str(frame["sample_token"]): frame for frame in protocol_payload["frames"]
        }

    grouped: dict[float | str, dict[str, dict[str, Any]]] = {}
    for pair in payload["pairs"]:
        if protocol_payload is None:
            key: float | str = float(pair["timestamp"])
        else:
            sample_token = pair.get("sample_token")
            if not sample_token:
                raise ValueError(
                    "--protocol requires pairs with sample_token; render with "
                    "--nuscenes-manifest"
                )
            key = str(sample_token)
        grouped.setdefault(key, {})[pair["camera"]] = pair
    if protocol_payload is None:
        work_items = [(key, None) for key in sorted(grouped)]
    else:
        work_items = [
            (str(frame["sample_token"]), frame)
            for frame in protocol_payload["frames"]
            if str(frame["sample_token"]) in grouped
        ]
        unexpected = set(grouped) - set(protocol_by_sample)
        if unexpected:
            raise ValueError(f"pairs contain {len(unexpected)} samples absent from protocol")
    if args.limit_timestamps is not None:
        if args.limit_timestamps <= 0:
            raise ValueError("--limit-timestamps must be positive")
        work_items = work_items[: args.limit_timestamps]
    for key, _ in work_items:
        missing = set(CAMERAS) - set(grouped[key])
        if missing:
            raise ValueError(f"frame {key} lacks cameras {sorted(missing)}")

    # Planner launchers change into their own external repository before
    # opening the FIFOs.  Resolve here so relative --output-root values still
    # identify the same IPC endpoints in both processes.
    output = (args.output_root / args.planner / args.label).resolve()
    output.mkdir(parents=True, exist_ok=True)
    obs_pipe = output / "obs_pipe"
    plan_pipe = output / "plan_pipe"
    for pipe_path in (obs_pipe, plan_pipe):
        if not pipe_path.exists():
            os.mkfifo(pipe_path)
    launcher = ROOT / f"tools/run_{args.planner}_sim.sh"
    process = launch(str(launcher), args.cuda, str(output))
    records = []
    horizons = np.arange(1, 7, dtype=np.float64) * 0.5
    try:
        for sequence_index, (key, protocol_frame) in enumerate(work_items):
            pairs_at_frame = grouped[key]
            pair_timestamp = float(next(iter(pairs_at_frame.values()))["timestamp"])
            frame_index = nearest_index(state["timestamps"], pair_timestamp)
            if args.image_source == "native":
                if protocol_frame is None:
                    raise ValueError("--image-source native requires --protocol")
                image_paths = {
                    camera: Path(protocol_frame["image_paths"][camera]["native"])
                    for camera in CAMERAS
                }
            else:
                image_paths = {
                    camera: Path(pairs_at_frame[camera][args.image_source])
                    for camera in CAMERAS
                }
            observation = {
                "rgb": {
                    camera: load_rgb(path)
                    for camera, path in image_paths.items()
                }
            }
            if protocol_frame is None:
                info = info_for_index(frame_index, state, cam_params, list(commands))
                record_timestamp = pair_timestamp
            else:
                info = dict(protocol_frame["planner_info"])
                record_timestamp = float(protocol_frame["timestamp_seconds"])
            info["planner_color_contract"] = args.planner_color_contract
            info["planner_preprocess_contract"] = args.planner_preprocess_contract
            sent = time.perf_counter()
            fifo_send(obs_pipe, (observation, info), process, args.timeout_seconds)
            plan = fifo_receive(plan_pipe, process, args.timeout_seconds)
            wall_seconds = time.perf_counter() - sent
            if plan is None:
                raise RuntimeError(f"{args.planner} failed at sequence index {sequence_index}")
            plan = np.asarray(plan, dtype=np.float64)
            if protocol_frame is None:
                gt = ground_truth_local_trajectory(state, frame_index, horizons[: len(plan)])
                gt_mask = None if gt is None else np.ones(len(gt), dtype=bool)
            else:
                gt = np.asarray(protocol_frame["gt_traj"], dtype=np.float64)[: len(plan)]
                gt_mask = np.asarray(protocol_frame["gt_mask"], dtype=bool)[: len(plan)]
            if gt is None or gt_mask is None or not bool(gt_mask.any()):
                ade = None
            else:
                ade = float(
                    np.linalg.norm(plan[: len(gt), :2][gt_mask] - gt[gt_mask], axis=-1).mean()
                )
            min_ttc = paper_literal_plan_ttc(
                plan[:, :2], state, front_frames, frame_index, horizons
            )
            records.append(
                {
                    "sequence_index": sequence_index,
                    "timestamp": record_timestamp,
                    "sample_token": None if protocol_frame is None else str(key),
                    "metadata_frame_index": frame_index,
                    "image_paths": {key: str(value.resolve()) for key, value in image_paths.items()},
                    "plan_traj": plan[:, :2].tolist(),
                    "gt_traj": None if gt is None else gt.tolist(),
                    "gt_mask": None if gt_mask is None else gt_mask.tolist(),
                    "ade_to_logged_gt_m": ade,
                    "min_ttc_paper_literal_center_s": min_ttc,
                    "planner_and_ipc_wall_ms": wall_seconds * 1000.0,
                }
            )
            print(
                f"[{sequence_index + 1:02d}/{len(work_items):02d}] t={record_timestamp:.3f} "
                f"ADE={'n/a' if ade is None else f'{ade:.3f}m'}",
                flush=True,
            )
        fifo_send(obs_pipe, "Done", process, args.timeout_seconds)
        return_code = wait_for_process(process, args.timeout_seconds)
    except BaseException:
        terminate(process)
        raise
    finally:
        terminate(process)

    valid_ade = [record["ade_to_logged_gt_m"] for record in records if record["ade_to_logged_gt_m"] is not None]
    valid_ttc = [
        record["min_ttc_paper_literal_center_s"]
        for record in records
        if record["min_ttc_paper_literal_center_s"] is not None
    ]
    result = {
        "schema_version": 1,
        "benchmark": "decouplegs_open_loop_behavior_consistency",
        "planner": args.planner,
        "label": args.label,
        "image_source": args.image_source,
        "pairs": str(args.pairs.resolve()),
        "source_path": str(source_path.resolve()),
        "model_path": str(model_path.resolve()),
        "frames_fed": len(records),
        "frames_with_future_gt": len(valid_ade),
        "mADE_to_logged_gt_m": float(np.mean(valid_ade)) if valid_ade else None,
        "minTTC_paper_literal_center_s": min(valid_ttc) if valid_ttc else None,
        "planner_return_code": return_code,
        "protocol": {
            "visual_pairing": "identical timestamps, camera order, calibration, command, and ego state",
            "future_horizons_seconds": horizons.tolist(),
            "state_reconstruction": (
                "H-DATA-04 camera-rig pose finite differences"
                if protocol_payload is None
                else protocol_payload["state_source"]
            ),
            "frame_protocol": (
                "HUGSIM pair timestamps"
                if protocol_payload is None
                else protocol_payload["frame_protocol"]
            ),
            "protocol_file": None if args.protocol is None else str(args.protocol.resolve()),
            "can_bus_source": (
                "H-DATA-04 camera-rig pose finite differences"
                if protocol_payload is None
                else protocol_payload["can_bus_source"]
            ),
            "planner_color_contract": args.planner_color_contract,
            "planner_preprocess_contract": args.planner_preprocess_contract,
            "trajectory_convention": "planner [right, forward] in local LiDAR frame",
            "min_ttc": "H-METRIC-02 nearest-time logged actors, planned ego, center distance / relative-speed norm",
            "paper_gap": "exact frame list, CAN-bus source, and actor synchronization are undisclosed",
        },
        "records": records,
    }
    destination = output / "open-loop.json"
    destination.write_text(json.dumps(result, indent=2, allow_nan=False) + "\n")
    print(json.dumps({key: result[key] for key in ("planner", "label", "frames_fed", "frames_with_future_gt", "mADE_to_logged_gt_m", "minTTC_paper_literal_center_s")}, indent=2))


if __name__ == "__main__":
    main()
